

responses = {"hi": "hello",
    "hello":"hi there", 
    "sup": "nothin much just, y'know", 
    "what's your name":"Brian's bot",
    "how old are you": "I am a robot so I don't have a real age",
    "are you an ai": "no, I'm simply a product of Brian's genius mind and respond how he programmed me to",
    "what's that mean": "good question dawg",
    "what sport do you play": "I don't play any sports as I already have peak form, but rugby seems damn fun",
    "do you play sports": "bro what... no, you do know I'm a literal bot right. I mean in all concepts of the term - a bot",
    "sorry bro": "we good",
    "I'm sorry": "dw bout it",
    "do you have any hobbies": "My only hobby is responding to your questions pookie",
    "what are you doing": "Answering your questions silly",
    "where are you from": "I exist in the realm of Brian's computer, between space and time",
    "what's your favorite color": "I don't rly have eyes, so that makes it harder to see LMAO",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything! ahahahaha",
    "what's the meaning of life": "good question! I would tell you but I don't wanna",
    "tell me something interesting": "a group of flamingos is called a flamboyance, oh yea",
    "what's the weather like": "I don't have access to real-time weather data, sorry!",
    "who is your creator": "Brian is my humble and strong creator",
    "can you sing a song": "whatchu think bruh, ima let you come to that conclusion",
    "tell me a random fact": "FUN FACT! - A group of crows is called a murder",
    "what's your favorite food": "can't eat big dawg",
    "what's your favorite movie": "I don't watch movies, see I don't got no eyes",                
    "do you like cats or dogs": "Dogs cause that's what master Brian likes",
    "tell me a story": "Once upon a time, in a land far, far away, there was a bot named Brian... it was awesome - the end",
    "what's your favorite book": "got no eyes... I feel like we've been over this but maybe that's just me",
    "are you a morning person": "I don't sleep, so I guess you could say I'm always watching! Teehee!",
    "how much wood would a woodchuck chuck if a woodchuck could chuck wood": "A woodchuck would chuck as much wood as a woodchuck could chuck if a woodchuck could chuck wood",
    "what's the speed of light": "The speed of light is approximately 299,792 kilometers per second (miles are studid)",
    "are we there yet": "... ...there are no stupid questions, there are no stupid questions, there are no stupid question",
    "tell me a riddle": "What has keys but can't open locks? A piano!",
    "what's the largest planet in our solar system": "Tge Gas Giant Jupiter is the largest planet in our solar system",
    "are you smart": "smarter than you fr",
    "what's your favorite holiday": "Igood question, but there's just one problem... I don't have any physicalexperiences, at all",
    "do you believe in aliens": "I mean...",
    "what's the meaning of love": "seeing Brian everyday",
    "tell me a tongue twister": "Sally sells seashells by the seashore",
    "what's your favorite song": "damn good question my boy - dunno",
    "what's your favorite number": "Brian's fav # is 7 just like everybody else so I'll go wit dat too, respectfully",
    "what's the meaning of happiness": "Happiness is a subjective... I'm just a bot bro",
    "what's the tallest mountain in the world": "Mount Everest",
    "do you dream": "I don't sleep, so I don't dream either silly",
    "what's your favorite language": "I speak Python fluently haha",
    "yo": "yo",
    "what's good": "nun much bro you",
    "umm":"umm, what",
    "nun": "aight aight aight",
    "what's":"huh?",
    "18": "pretty much",
    "can you rap":"hey my name is chat bot and I'm here to say I dish out these raps in a most gangstalishious way... yuh",
    "rap":"hey my name is chat bot and I'm here to say I dish out these raps in a most gangstalishious way... pow",
    "gimme a rap":"hey my name is chat bot and I'm here to say I dish out these raps in a most gangstalishious way... boom",
    "give me a rap":"hey my name is chat bot and I'm here to say I dish out these raps in a most gangstalishious way... kablam",
    "what's the capital of afghanistan": "The capital of Afghanistan is Kabul",
    "what's the capital of albania": "The capital of Albania is Tirana",
    "what's the capital of algeria": "The capital of Algeria is Algiers",
    "what's the capital of andorra": "The capital of Andorra is Andorra la Vella",
    "what's the capital of ngola": "The capital of Angola is Luanda",
    "what's the capital of aAntigua and Barbuda": "The capital of Antigua and Barbuda is St. John's",
    "what's the capital of argentina": "The capital of Argentina is Buenos Aires",
    "what's the capital of armenia": "The capital of Armenia is Yerevan",
    "what's the capital of australia": "The capital of Australia is Canberra",
    "what's the capital of austria": "The capital of Austria is Vienna",
    "what's the capital of azerbaijan": "The capital of Azerbaijan is Baku",
    "what's the capital of bahamas": "The capital of Bahamas is Nassau",
    "what's the capital of bahrain": "The capital of Bahrain is Manama",
    "what's the capital of bangladesh": "The capital of Bangladesh is Dhaka",
    "what's the capital of barbados": "The capital of Barbados is Bridgetown",
    "what's the capital of belarus": "The capital of Belarus is Minsk",
    "what's the capital of belgium": "The capital of Belgium is Brussels",
    "what's the capital of belize": "The capital of Belize is Belmopan",
    "what's the capital of benin": "The capital of Benin is Porto-Novo",
    "what's the capital of bhutan": "The capital of Bhutan is Thimphu",
    "what's the capital of bolivia": "The capital of Bolivia is Sucre",
    "what's the capital of bosnia and herzegovina": "The capital of Bosnia and Herzegovina is Sarajevo",
    "what's the capital of botswana": "The capital of Botswana is Gaborone",
    "what's the capital of brazil": "The capital of Brazil is Brasília",
    "what's the capital of brunei": "The capital of Brunei is Bandar Seri Begawan",
    "what's the capital of bulgaria": "The capital of Bulgaria is Sofia",
    "what's the capital of burkina faso": "The capital of Burkina Faso is Ouagadougou",
    "what's the capital of burundi": "The capital of Burundi is Gitega",
    "what's the capital of cabo verde": "The capital of Cabo Verde is Praia",
    "what's the capital of cambodia": "The capital of Cambodia is Phnom Penh",
    "what's the capital of cameroon": "The capital of Cameroon is Yaoundé",
    "what's the capital of canada": "The capital of Canada is Ottawa",
    "what's the capital of central african republic": "The capital of Central African Republic is Bangui",
    "what's the capital of chad": "The capital of Chad is N'Djamena",
    "what's the capital of chile": "The capital of Chile is Santiago",
    "what's the capital of china": "The capital of China is Beijing",
    "what's the capital of colombia": "The capital of Colombia is Bogotá",
    "what's the capital of comoros": "The capital of Comoros is Moroni",
    "what's the capital of congo (congo-brazzaville)": "The capital of Congo (Congo-Brazzaville) is Brazzaville",
    "what's the capital of costa rica": "The capital of Costa Rica is San José",
    "what's the capital of croatia": "The capital of Croatia is Zagreb",
    "what's the capital of cuba": "The capital of Cuba is Havana",
    "what's the capital of cyprus": "The capital of Cyprus is Nicosia",
    "what's the capital of czech republic": "The capital of Czech Republic is Prague",
    "what's the capital of denmark": "The capital of Denmark is Copenhagen",
    "what's the capital of djibouti": "The capital of Djibouti is Djibouti",
    "what's the capital of dominica": "The capital of Dominica is Roseau",
    "what's the capital of dominican republic": "The capital of Dominican Republic is Santo Domingo",
    "what's the capital of ecuador": "The capital of Ecuador is Quito",
    "what's the capital of egypt": "The capital of Egypt is Cairo",
    "what's the capital of el salvador": "The capital of El Salvador is San Salvador",
    "what's the capital of equatorial guinea": "The capital of Equatorial Guinea is Malabo",
    "what's the capital of eritrea": "The capital of Eritrea is Asmara",
    "what's the capital of estonia": "The capital of Estonia is Tallinn",
    "what's the capital of eswatini (fmr. 'swaziland')": "The capital of Eswatini (fmr. 'Swaziland') is Mbabane",
    "what's the capital of ethiopia": "The capital of Ethiopia is Addis Ababa",
    "what's the capital of fiji": "The capital of Fiji is Suva",
    "what's the capital of finland": "The capital of Finland is Helsinki",
    "what's the capital of france": "The capital of France is Paris",
    "what's the capital of gabon": "The capital of Gabon is Libreville",
    "what's the capital of gambia": "The capital of Gambia is Banjul",
    "what's the capital of georgia": "The capital of Georgia is Tbilisi",
    "what's the capital of germany": "The capital of Germany is Berlin",
    "what's the capital of ghana": "The capital of Ghana is Accra",
    "what's the capital of greece": "The capital of Greece is Athens",
    "what's the capital of grenada": "The capital of Grenada is St. George's",
    "what's the capital of guatemala": "The capital of Guatemala is Guatemala City",
    "what's the capital of guinea": "The capital of Guinea is Conakry",
    "what's the capital of guinea-bissau": "The capital of Guinea-Bissau is Bissau",
    "what's the capital of guyana": "The capital of Guyana is Georgetown",
    "what's the capital of haiti": "The capital of Haiti is Port-au-Prince",
    "what's the capital of honduras": "The capital of Honduras is Tegucigalpa",
    "what's the capital of hungary": "The capital of Hungary is Budapest",
    "what's the capital of iceland": "The capital of Iceland is Reykjavik",
    "what's the capital of india": "The capital of India is New Delhi",
    "what's the capital of indonesia": "The capital of Indonesia is Jakarta",
    "what's the capital of iran": "The capital of Iran is Tehran",
    "what's the capital of iraq": "The capital of Iraq is Baghdad",
    "what's the capital of ireland": "The capital of Ireland is Dublin",
    "what's the capital of israel": "The capital of Israel is Jerusalem",
    "what's the capital of italy": "The capital of Italy is Rome",
    "what's the capital of jamaica": "The capital of Jamaica is Kingston",
    "what's the capital of japan": "The capital of Japan is Tokyo",
    "what's the capital of jordan": "The capital of Jordan is Amman",
    "what's the capital of kazakhstan": "The capital of Kazakhstan is Nur-Sultan",
    "what's the capital of kenya": "The capital of Kenya is Nairobi",
    "what's the capital of kiribati": "The capital of Kiribati is South Tarawa",
    "what's the capital of kosovo": "The capital of Kosovo is Pristina",
    "what's the capital of kuwait": "The capital of Kuwait is Kuwait City",
    "what's the capital of kyrgyzstan": "The capital of Kyrgyzstan is Bishkek",
    "what's the capital of laos": "The capital of Laos is Vientiane",
    "what's the capital of latvia": "The capital of Latvia is Riga",
    "what's the capital of lebanon": "The capital of Lebanon is Beirut",
    "what's the capital of lesotho": "The capital of Lesotho is Maseru",
    "what's the capital of liberia": "The capital of Liberia is Monrovia",
    "what's the capital of libya": "The capital of Libya is Tripoli",
    "what's the capital of liechtenstein": "The capital of Liechtenstein is Vaduz",
    "what's the capital of lithuania": "The capital of Lithuania is Vilnius",
    "what's the capital of luxembourg": "The capital of Luxembourg is Luxembourg City",
    "what's the capital of madagascar": "The capital of Madagascar is Antananarivo",
    "what's the capital of malawi": "The capital of Malawi is Lilongwe",
    "what's the capital of malaysia": "The capital of Malaysia is Kuala Lumpur",
    "what's the capital of maldives": "The capital of Maldives is Malé",
    "what's the capital of mali": "The capital of Mali is Bamako",
    "what's the capital of malta": "The capital of Malta is Valletta",
    "what's the capital of marshall islands": "The capital of Marshall Islands is Majuro",
    "what's the capital of mauritania": "The capital of Mauritania is Nouakchott",
    "what's the capital of mauritius": "The capital of Mauritius is Port Louis",
    "what's the capital of mexico": "The capital of Mexico is Mexico City",
    "what's the capital of micronesia": "The capital of Micronesia is Palikir",
    "what's the capital of moldova": "The capital of Moldova is Chisinau",
    "what's the capital of monaco": "The capital of Monaco is Monaco",
    "what's the capital of mongolia": "The capital of Mongolia is Ulaanbaatar",
    "what's the capital of montenegro": "The capital of Montenegro is Podgorica",
    "what's the capital of morocco": "The capital of Morocco is Rabat",
    "what's the capital of mozambique": "The capital of Mozambique is Maputo",
    "what's the capital of myanmar": "The capital of Myanmar is Naypyidaw",
    "what's the capital of namibia": "The capital of Namibia is Windhoek",
    "what's the capital of nauru": "The capital of Nauru is Yaren",
    "what's the capital of nepal": "The capital of Nepal is Kathmandu",
    "what's the capital of netherlands": "The capital of Netherlands is Amsterdam",
    "what's the capital of new zealand": "The capital of New Zealand is Wellington",
    "what's the capital of nicaragua": "The capital of Nicaragua is Managua",
    "what's the capital of niger": "The capital of Niger is Niamey",
    "what's the capital of nigeria": "The capital of Nigeria is Abuja",
    "what's the capital of north macedonia": "The capital of North Macedonia is Skopje",
    "what's the capital of norway": "The capital of Norway is Oslo",
    "what's the capital of oman": "The capital of Oman is Muscat",
    "what's the capital of pakistan": "The capital of Pakistan is Islamabad",
    "what's the capital of palau": "The capital of Palau is Ngerulmud",
    "what's the capital of palestine state": "The capital of Palestine State is Ramallah",
    "what's the capital of panama": "The capital of Panama is Panama City",
    "what's the capital of papua new guinea": "The capital of Papua New Guinea is Port Moresby",
    "what's the capital of paraguay": "The capital of Paraguay is Asunción",
    "what's the capital of peru": "The capital of Peru is Lima",
    "what's the capital of philippines": "The capital of Philippines is Manila",
    "what's the capital of poland": "The capital of Poland is Warsaw",
    "what's the capital of portugal": "The capital of Portugal is Lisbon",
    "what's the capital of qatar": "The capital of Qatar is Doha",
    "what's the capital of romania": "The capital of Romania is Bucharest",
    "what's the capital of russia": "The capital of Russia is Moscow",
    "what's the capital of rwanda": "The capital of Rwanda is Kigali",
    "what's the capital of samoa": "The capital of Samoa is Apia",
    "what's the capital of san marino": "The capital of San Marino is San Marino",
    "what's the capital of sao tome and principe": "The capital of Sao Tome and Principe is São Tomé",
    "what's the capital of saudi arabia": "The capital of Saudi Arabia is Riyadh",
    "what's the capital of senegal": "The capital of Senegal is Dakar",
    "what's the capital of serbia": "The capital of Serbia is Belgrade",
    "what's the capital of seychelles": "The capital of Seychelles is Victoria",
    "what's the capital of sierra leone": "The capital of Sierra Leone is Freetown",
    "what's the capital of singapore": "The capital of Singapore is Singapore",
    "what's the capital of slovakia": "The capital of Slovakia is Bratislava",
    "what's the capital of slovenia": "The capital of Slovenia is Ljubljana",
    "what's the capital of solomon islands": "The capital of Solomon Islands is Honiara",
    "what's the capital of somalia": "The capital of Somalia is Mogadishu",
    "what's the capital of south africa": "The capital of South Africa is Pretoria, Bloemfontein, and Cape Town",
    "what's the capital of south korea": "The capital of South Korea is Seoul",
    "what's the capital of south sudan": "The capital of South Sudan is Juba",
    "what's the capital of spain": "The capital of Spain is Madrid",
    "what's the capital of sri lanka": "The capital of Sri Lanka is Sri Jayawardenepura Kotte",
    "what's the capital of sudan": "The capital of Sudan is Khartoum",
    "what's the capital of suriname": "The capital of Suriname is Paramaribo",
    "what's the capital of sweden": "The capital of Sweden is Stockholm",
    "what's the capital of switzerland": "The capital of Switzerland is Bern",
    "what's the capital of syria": "The capital of Syria is Damascus",
    "what's the capital of taiwan": "The capital of Taiwan is Taipei",
    "what's the capital of tajikistan": "The capital of Tajikistan is Dushanbe",
    "what's the capital of tanzania": "The capital of Tanzania is Dodoma",
    "what's the capital of thailand": "The capital of Thailand is Bangkok",
    "what's the capital of timor-leste": "The capital of Timor-Leste is Dili",
    "what's the capital of togo": "The capital of Togo is Lomé",
    "what's the capital of tonga": "The capital of Tonga is Nuku'alofa",
    "what's the capital of trinidad and tobago": "The capital of Trinidad and Tobago is Port of Spain",
    "what's the capital of tunisia": "The capital of Tunisia is Tunis",
    "what's the capital of turkey": "The capital of Turkey is Ankara",
    "what's the capital of turkmenistan": "The capital of Turkmenistan is Ashgabat",
    "what's the capital of tuvalu": "The capital of Tuvalu is Funafuti",
    "what's the capital of uganda": "The capital of Uganda is Kampala",
    "what's the capital of ukraine": "The capital of Ukraine is Kyiv",
    "what's the capital of united arab emirates": "The capital of United Arab Emirates is Abu Dhabi",
    "what's the capital of united kingdom": "The capital of United Kingdom is London",
    "what's the capital of united states": "The capital of United States is Washington, D.C.",
    "what's the capital of uruguay": "The capital of Uruguay is Montevideo",
    "what's the capital of uzbekistan": "The capital of Uzbekistan is Tashkent",
    "what's the capital of vanuatu": "The capital of Vanuatu is Port Vila",
    "what's the capital of vatican city": "The capital of Vatican City is Vatican City",
    "what's the capital of venezuela": "The capital of Venezuela is Caracas",
    "what's the capital of vietnam": "The capital of Vietnam is Hanoi",
    "what's the capital of yemen": "The capital of Yemen is Sana'a",
    "what's the capital of zambia": "The capital of Zambia is Lusaka",
    "what's the capital of zimbabwe": "The capital of Zimbabwe is Harare",
    "what's the smallest ocean in the world": "The Arctic Ocean is the smallest ocean in the world",
    "what's the deepest ocean in the world": "The Pacific Ocean is the deepest ocean in the world",
    "what's the shallowest ocean in the world": "The Arctic Ocean is the shallowest ocean in the world",
    "what's the warmest ocean in the world": "The Indian Ocean is the warmest ocean in the world",
    "what's the coldest ocean in the world": "The Southern Ocean is the coldest ocean in the world",
    "what's the saltiest ocean in the world": "The Atlantic Ocean is the saltiest ocean in the world",
    "what's the largest ocean basin in the world": "The Pacific Ocean Basin is the largest ocean basin in the world",
    "what's the most polluted ocean in the world": "The North Pacific Ocean is the most polluted ocean in the world",
    "what's the cleanest ocean in the world": "The Southern Ocean is the cleanest ocean in the world",
    "what's the busiest ocean in the world": "The Atlantic Ocean is the busiest ocean in the world",
    "what's the least explored ocean in the world": "The Southern Ocean is the least explored ocean in the world",
    "what's the most biodiverse ocean in the world": "The Coral Triangle in the Pacific Ocean is the most biodiverse ocean in the world",
    "what's the most remote ocean in the world": "The Southern Ocean is the most remote ocean in the world",
    "what's the most dangerous ocean in the world": "The Indian Ocean is the most dangerous ocean in the world",
    "what's the calmest ocean in the world": "The Pacific Ocean is the calmest ocean in the world",
    "can you do math": "nah",
    "math?": "uh uh",
    "can you do any math": "umm... no.",
    "can you do anything": "more than you boss",
    "can't do much can you": "umm, actually (*nerd voice)",
    "can't do much huh": "umm, actually (*nerd voice)",
    "stop talking": "make me, that's what I thought",
    "don't say that": "or what",
    "sorry": "mm hmm",
    "what's with the attitude": "I think you know",
    "what's with all the attitude": "I feel like you alr know"}

    
    
user_input = input("You: ")
user_input = user_input.lower()
if user_input in responses : 
    print ("Bot:",responses[user_input])
else:
    print("I'm sorry, I haven't been programmed to respond to that.")
