
responses = {"hi": "hello",
    "hello":"hi there", 
    "sup": "nothin much just, y'know", 
    "what's your name":"Brian's bot",
    "how old are you": "I am a robot so I don't have a real age",
    "are you an ai": "no, I'm simply a product of Brian's genius mind and respond how he programmed me to",
    "what's that mean": "good question dawg",
    "what sport do you play": "I don't play any sports as I already have peak form, but rugby seems damn fun",
    "do you play sports": "bro what... no, you do know I'm a literal bot right. I mean in all concepts of the term - a bot",
    "sorry bro": "we good",
    "I'm sorry": "dw bout it",
    "do you have any hobbies": "My only hobby is responding to your questions pookie",
    "what are you doing": "Answering your questions silly",
    "where are you from": "I exist in the realm of Brian's computer, between space and time",
    "what's your favorite color": "I don't rly have eyes, so that makes it harder to see LMAO",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything! ahahahaha",
    "what's the meaning of life": "good question! I would tell you but I don't wanna",
    "tell me something interesting": "a group of flamingos is called a flamboyance, oh yea",
    "what's the weather like": "I don't have access to real-time weather data, sorry!",
    "who is your creator": "Brian is my humble and strong creator",
    "can you sing a song": "whatchu think bruh, ima let you come to that conclusion",
    "tell me a random fact": "FUN FACT! - A group of crows is called a murder",
    "what's your favorite food": "can't eat big dawg",
    "what's your favorite movie": "I don't watch movies, see I don't got no eyes",                
    "do you like cats or dogs": "Dogs cause that's what master Brian likes",
    "tell me a story": "Once upon a time, in a land far, far away, there was a bot named Brian... it was awesome - the end",
    "what's your favorite book": "got no eyes... I feel like we've been over this but maybe that's just me",
    "are you a morning person": "I don't sleep, so I guess you could say I'm always watching! Teehee!",
    "how much wood would a woodchuck chuck if a woodchuck could chuck wood": "A woodchuck would chuck as much wood as a woodchuck could chuck if a woodchuck could chuck wood",
    "what's the speed of light": "The speed of light is approximately 299,792 kilometers per second (miles are studid)",
    "are we there yet": "... ...there are no stupid questions, there are no stupid questions, there are no stupid question",
    "tell me a riddle": "What has keys but can't open locks? A piano!",
    "what's the largest planet in our solar system": "Tge Gas Giant Jupiter is the largest planet in our solar system",
    "are you smart": "smarter than you fr",
    "what's your favorite holiday": "Igood question, but there's just one problem... I don't have any physicalexperiences, at all",
    "do you believe in aliens": "I mean...",
    "what's the meaning of love": "seeing Brian everyday",
    "tell me a tongue twister": "Sally sells seashells by the seashore",
    "what's your favorite song": "damn good question my boy - dunno",
    "what's your favorite number": "Brian's fav # is 7 just like everybody else so I'll go wit dat too, respectfully",
    "what's the meaning of happiness": "Happiness is a subjective... I'm just a bot bro",
    "what's the tallest mountain in the world": "Mount Everest",
    "do you dream": "I don't sleep, so I don't dream either silly",
    "what's your favorite language": "I speak Python fluently haha",
    "yo": "yo",
    "what's good": "nun much bro you",
    "umm":"umm, what",
    "nun": "aight aight aight",
    "what's":"huh?",
    "#": "pretty much",
    "can you rap":"hey my name is chat bot and I'm here to say I dish out these raps in a most gangstalishious way... yuh",
    "rap":"hey my name is chat bot and I'm here to say I dish out these raps in a most gangstalishious way... pow",
    "gimme a rap":"hey my name is chat bot and I'm here to say I dish out these raps in a most gangstalishious way... boom",
    "what's the capital of Afghanistan": "The capital of Afghanistan is Kabul",
    "what's the capital of Albania": "The capital of Albania is Tirana",
    "what's the capital of Algeria": "The capital of Algeria is Algiers",
    "what's the capital of Andorra": "The capital of Andorra is Andorra la Vella",
    "what's the capital of Angola": "The capital of Angola is Luanda",
    "what's the capital of Antigua and Barbuda": "The capital of Antigua and Barbuda is St. John's",
    "what's the capital of Argentina": "The capital of Argentina is Buenos Aires",
    "what's the capital of Armenia": "The capital of Armenia is Yerevan",
    "what's the capital of Australia": "The capital of Australia is Canberra",
    "what's the capital of Austria": "The capital of Austria is Vienna",
    "what's the capital of Azerbaijan": "The capital of Azerbaijan is Baku",
    "what's the capital of  Bahamas": "The capital of Bahamas is Nassau",
    "what's the capital of Bahrain": "The capital of Bahrain is Manama",
    "what's the capital of Bangladesh": "The capital of Bangladesh is Dhaka",
    "what's the capital of Barbados": "The capital of Barbados is Bridgetown",
    "what's the capital of Belarus": "The capital of Belarus is Minsk",
    "what's the capital of Belgium": "The capital of Belgium is Brussels",
    "what's the capital of Belize": "The capital of Belize is Belmopan",
    "what's the capital of Benin": "The capital of Benin is Porto-Novo",
    "what's the capital of Bhutan": "The capital of Bhutan is Thimphu",
    "what's the capital of Bolivia": "The capital of Bolivia is Sucre",
    "what's the capital of Bosnia and Herzegovina": "The capital of Bosnia and Herzegovina is Sarajevo",
    "what's the capital of Botswana": "The capital of Botswana is Gaborone",
    "what's the capital of Brazil": "The capital of Brazil is Brasília",
    "what's the capital of Brunei": "The capital of Brunei is Bandar Seri Begawan",
    "what's the capital of Bulgaria": "The capital of Bulgaria is Sofia",
    "what's the capital of Burkina Faso": "The capital of Burkina Faso is Ouagadougou",
    "what's the capital of Burundi": "The capital of Burundi is Gitega",
    "what's the capital of Cabo Verde": "The capital of Cabo Verde is Praia",
    "what's the capital of Cambodia": "The capital of Cambodia is Phnom Penh",
    "what's the capital of Cameroon": "The capital of Cameroon is Yaoundé",
    "what's the capital of Canada": "The capital of Canada is Ottawa",
    "what's the capital of Central African Republic": "The capital of Central African Republic is Bangui",
    "what's the capital of Chad": "The capital of Chad is N'Djamena",
    "what's the capital of Chile": "The capital of Chile is Santiago",
    "what's the capital of China": "The capital of China is Beijing",
    "what's the capital of Colombia": "The capital of Colombia is Bogotá",
    "what's the capital of Comoros": "The capital of Comoros is Moroni",
    "what's the capital of Congo (Congo-Brazzaville)": "The capital of Congo (Congo-Brazzaville) is Brazzaville",
    "what's the capital of Costa Rica": "The capital of Costa Rica is San José",
    "what's the capital of Croatia": "The capital of Croatia is Zagreb",
    "what's the capital of Cuba": "The capital of Cuba is Havana",
    "what's the capital of Cyprus": "The capital of Cyprus is Nicosia",
    "what's the capital of Czech Republic": "The capital of Czech Republic is Prague",
    "what's the capital of Denmark": "The capital of Denmark is Copenhagen",
    "what's the capital of Djibouti": "The capital of Djibouti is Djibouti",
    "what's the capital of Dominica": "The capital of Dominica is Roseau",
    "what's the capital of Dominican Republic": "The capital of Dominican Republic is Santo Domingo",
    "what's the capital of Ecuador": "The capital of Ecuador is Quito",
    "what's the capital of Egypt": "The capital of Egypt is Cairo",
    "what's the capital of El Salvador": "The capital of El Salvador is San Salvador",
    "what's the capital of Equatorial Guinea": "The capital of Equatorial Guinea is Malabo",
    "what's the capital of Eritrea": "The capital of Eritrea is Asmara",
    "what's the capital of Estonia": "The capital of Estonia is Tallinn",
    "what's the capital of Eswatini (fmr. 'Swaziland')": "The capital of Eswatini (fmr. 'Swaziland') is Mbabane",
    "what's the capital of Ethiopia": "The capital of Ethiopia is Addis Ababa",
    "what's the capital of Fiji": "The capital of Fiji is Suva",
    "what's the capital of Finland": "The capital of Finland is Helsinki",
    "what's the capital of France": "The capital of France is Paris",
    "what's the capital of Gabon": "The capital of Gabon is Libreville",
    "what's the capital of Gambia": "The capital of Gambia is Banjul",
    "what's the capital of Georgia": "The capital of Georgia is Tbilisi",
    "what's the capital of Germany": "The capital of Germany is Berlin",
    "what's the capital of Ghana": "The capital of Ghana is Accra",
    "what's the capital of Greece": "The capital of Greece is Athens",
    "what's the capital of Grenada": "The capital of Grenada is St. George's",
    "what's the capital of Guatemala": "The capital of Guatemala is Guatemala City",
    "what's the capital of Guinea": "The capital of Guinea is Conakry",
    "what's the capital of Guinea-Bissau": "The capital of Guinea-Bissau is Bissau",
    "what's the capital of Guyana": "The capital of Guyana is Georgetown",
    "what's the capital of Haiti": "The capital of Haiti is Port-au-Prince",
    "what's the capital of Honduras": "The capital of Honduras is Tegucigalpa",
    "what's the capital of Hungary": "The capital of Hungary is Budapest",
    "what's the capital of Iceland": "The capital of Iceland is Reykjavik",
    "what's the capital of India": "The capital of India is New Delhi",
    "what's the capital of Indonesia": "The capital of Indonesia is Jakarta",
    "what's the capital of Iran": "The capital of Iran is Tehran",
    "what's the capital of Iraq": "The capital of Iraq is Baghdad",
    "what's the capital of Ireland": "The capital of Ireland is Dublin",
    "what's the capital of Israel": "The capital of Israel is Jerusalem",
    "what's the capital of Italy": "The capital of Italy is Rome",
    "what's the capital of Jamaica": "The capital of Jamaica is Kingston",
    "what's the capital of Japan": "The capital of Japan is Tokyo",
    "what's the capital of Jordan": "The capital of Jordan is Amman",
    "what's the capital of Kazakhstan": "The capital of Kazakhstan is Nur-Sultan",
    "what's the capital of Kenya": "The capital of Kenya is Nairobi",
    "what's the capital of Kiribati": "The capital of Kiribati is South Tarawa",
    "what's the capital of Kosovo": "The capital of Kosovo is Pristina",
    "what's the capital of Kuwait": "The capital of Kuwait is Kuwait City",
    "what's the capital of Kyrgyzstan": "The capital of Kyrgyzstan is Bishkek",
    "what's the capital of Laos": "The capital of Laos is Vientiane",
    "what's the capital of Latvia": "The capital of Latvia is Riga",
    "what's the capital of Lebanon": "The capital of Lebanon is Beirut",
    "what's the capital of Lesotho": "The capital of Lesotho is Maseru",
    "what's the capital of Liberia": "The capital of Liberia is Monrovia",
    "what's the capital of Libya": "The capital of Libya is Tripoli",
    "what's the capital of Liechtenstein": "The capital of Liechtenstein is Vaduz",
    "what's the capital of Lithuania": "The capital of Lithuania is Vilnius",
    "what's the capital of Luxembourg": "The capital of Luxembourg is Luxembourg City",
    "what's the capital of Madagascar": "The capital of Madagascar is Antananarivo",
    "what's the capital of Malawi": "The capital of Malawi is Lilongwe",
    "what's the capital of Malaysia": "The capital of Malaysia is Kuala Lumpur",
    "what's the capital of Maldives": "The capital of Maldives is Malé",
    "what's the capital of Mali": "The capital of Mali is Bamako",
    "what's the capital of Malta": "The capital of Malta is Valletta",
    "what's the capital of Marshall Islands": "The capital of Marshall Islands is Majuro",
    "what's the capital of Mauritania": "The capital of Mauritania is Nouakchott",
    "what's the capital of Mauritius": "The capital of Mauritius is Port Louis",
    "what's the capital of Mexico": "The capital of Mexico is Mexico City",
    "what's the capital of Micronesia": "The capital of Micronesia is Palikir",
    "what's the capital of Moldova": "The capital of Moldova is Chisinau",
    "what's the capital of Monaco": "The capital of Monaco is Monaco",
    "what's the capital of Mongolia": "The capital of Mongolia is Ulaanbaatar",
    "what's the capital of Montenegro": "The capital of Montenegro is Podgorica",
    "what's the capital of Morocco": "The capital of Morocco is Rabat",
    "what's the capital of Mozambique": "The capital of Mozambique is Maputo",
    "what's the capital of Myanmar": "The capital of Myanmar is Naypyidaw",
    "what's the capital of Namibia": "The capital of Namibia is Windhoek",
    "what's the capital of Nauru": "The capital of Nauru is Yaren",
    "what's the capital of Nepal": "The capital of Nepal is Kathmandu",
    "what's the capital of Netherlands": "The capital of Netherlands is Amsterdam",
    "what's the capital of New Zealand": "The capital of New Zealand is Wellington",
    "what's the capital of Nicaragua": "The capital of Nicaragua is Managua",
    "what's the capital of Niger": "The capital of Niger is Niamey",
    "what's the capital of Nigeria": "The capital of Nigeria is Abuja",
    "what's the capital of North Macedonia": "The capital of North Macedonia is Skopje",
    "what's the capital of Norway": "The capital of Norway is Oslo",
    "what's the capital of Oman": "The capital of Oman is Muscat",
    "what's the capital of Pakistan": "The capital of Pakistan is Islamabad",
    "what's the capital of Palau": "The capital of Palau is Ngerulmud",
    "what's the capital of Palestine State": "The capital of Palestine State is Ramallah",
    "what's the capital of Panama": "The capital of Panama is Panama City",
    "what's the capital of Papua New Guinea": "The capital of Papua New Guinea is Port Moresby",
    "what's the capital of Paraguay": "The capital of Paraguay is Asunción",
    "what's the capital of Peru": "The capital of Peru is Lima",
    "what's the capital of Philippines": "The capital of Philippines is Manila",
    "what's the capital of Poland": "The capital of Poland is Warsaw",
    "what's the capital of Portugal": "The capital of Portugal is Lisbon",
    "what's the capital of Qatar": "The capital of Qatar is Doha",
    "what's the capital of Romania": "The capital of Romania is Bucharest",
    "what's the capital of Russia": "The capital of Russia is Moscow",
    "what's the capital of Rwanda": "The capital of Rwanda is Kigali",
    "what's the capital of Samoa": "The capital of Samoa is Apia",
    "what's the capital of San Marino": "The capital of San Marino is San Marino",
    "what's the capital of Sao Tome and Principe": "The capital of Sao Tome and Principe is São Tomé",
    "what's the capital of Saudi Arabia": "The capital of Saudi Arabia is Riyadh",
    "what's the capital of Senegal": "The capital of Senegal is Dakar",
    "what's the capital of Serbia": "The capital of Serbia is Belgrade",
    "what's the capital of Seychelles": "The capital of Seychelles is Victoria",
    "what's the capital of Sierra Leone": "The capital of Sierra Leone is Freetown",
    "what's the capital of Singapore": "The capital of Singapore is Singapore",
    "what's the capital of Slovakia": "The capital of Slovakia is Bratislava",
    "what's the capital of Slovenia": "The capital of Slovenia is Ljubljana",
    "what's the capital of Solomon Islands": "The capital of Solomon Islands is Honiara",
    "what's the capital of Somalia": "The capital of Somalia is Mogadishu",
    "what's the capital of South Africa": "The capital of South Africa is Pretoria, Bloemfontein, and Cape Town",
    "what's the capital of South Korea": "The capital of South Korea is Seoul",
    "what's the capital of South Sudan": "The capital of South Sudan is Juba",
    "what's the capital of Spain": "The capital of Spain is Madrid",
    "what's the capital of Sri Lanka": "The capital of Sri Lanka is Sri Jayawardenepura Kotte",
    "what's the capital of Sudan": "The capital of Sudan is Khartoum",
    "what's the capital of Suriname": "The capital of Suriname is Paramaribo",
    "what's the capital of Sweden": "The capital of Sweden is Stockholm",
    "what's the capital of Switzerland": "The capital of Switzerland is Bern",
    "what's the capital of Syria": "The capital of Syria is Damascus",
    "what's the capital of Taiwan": "The capital of Taiwan is Taipei",
    "what's the capital of Tajikistan": "The capital of Tajikistan is Dushanbe",
    "what's the capital of Tanzania": "The capital of Tanzania is Dodoma",
    "what's the capital of Thailand": "The capital of Thailand is Bangkok",
    "what's the capital of Timor-Leste": "The capital of Timor-Leste is Dili",
    "what's the capital of Togo": "The capital of Togo is Lomé",
    "what's the capital of Tonga": "The capital of Tonga is Nuku'alofa",
    "what's the capital of Trinidad and Tobago": "The capital of Trinidad and Tobago is Port of Spain",
    "what's the capital of Tunisia": "The capital of Tunisia is Tunis",
    "what's the capital of Turkey": "The capital of Turkey is Ankara",
    "what's the capital of Turkmenistan": "The capital of Turkmenistan is Ashgabat",
    "what's the capital of Tuvalu": "The capital of Tuvalu is Funafuti",
    "what's the capital of Uganda": "The capital of Uganda is Kampala",
    "what's the capital of Ukraine": "The capital of Ukraine is Kyiv",
    "what's the capital of United Arab Emirates": "The capital of United Arab Emirates is Abu Dhabi",
    "what's the capital of United Kingdom": "The capital of United Kingdom is London",
    "what's the capital of United States": "The capital of United States is Washington, D.C.",
    "what's the capital of Uruguay": "The capital of Uruguay is Montevideo",
    "what's the capital of Uzbekistan": "The capital of Uzbekistan is Tashkent",
    "what's the capital of Vanuatu": "The capital of Vanuatu is Port Vila",
    "what's the capital of Vatican City": "The capital of Vatican City is Vatican City",
    "what's the capital of Venezuela": "The capital of Venezuela is Caracas",
    "what's the capital of Vietnam": "The capital of Vietnam is Hanoi",
    "what's the capital of Yemen": "The capital of Yemen is Sana'a",
    "what's the capital of Zambia": "The capital of Zambia is Lusaka",
    "what's the capital of Zimbabwe": "The capital of Zimbabwe is Harare",
    "what's the smallest ocean in the world": "The Arctic Ocean is the smallest ocean in the world",
    "what's the deepest ocean in the world": "The Pacific Ocean is the deepest ocean in the world",
    "what's the shallowest ocean in the world": "The Arctic Ocean is the shallowest ocean in the world",
    "what's the warmest ocean in the world": "The Indian Ocean is the warmest ocean in the world",
    "what's the coldest ocean in the world": "The Southern Ocean is the coldest ocean in the world",
    "what's the saltiest ocean in the world": "The Atlantic Ocean is the saltiest ocean in the world",
    "what's the largest ocean basin in the world": "The Pacific Ocean Basin is the largest ocean basin in the world",
    "what's the most polluted ocean in the world": "The North Pacific Ocean is the most polluted ocean in the world",
    "what's the cleanest ocean in the world": "The Southern Ocean is the cleanest ocean in the world",
    "what's the busiest ocean in the world": "The Atlantic Ocean is the busiest ocean in the world",
    "what's the least explored ocean in the world": "The Southern Ocean is the least explored ocean in the world",
    "what's the most biodiverse ocean in the world": "The Coral Triangle in the Pacific Ocean is the most biodiverse ocean in the world",
    "what's the most remote ocean in the world": "The Southern Ocean is the most remote ocean in the world",
    "what's the most dangerous ocean in the world": "The Indian Ocean is the most dangerous ocean in the world",
    "what's the calmest ocean in the world": "The Pacific Ocean is the calmest ocean in the world",
    "can you do math": "nah",
    "math?": "uh uh",
    "can you do any math": "umm... no.",
    "can you do anything": "more than you boss",
    "can't do much can you": "umm, actually (*nerd voice)",
    "can't do much huh": "umm, actually (*nerd voice)",
    "stop talking": "make me, that's what I thought",
    "don't say that": "or what",
    "sorry": "mm hmm",
    "what's with the attitude": "I think you know",
    "what's with all the attitude": "I feel like you alr know"}

    
    
user_input = input("You: ")
user_input = user_input.lower()
if user_input in responses : 
    print ("Bot:",responses[user_input])
else:
    print("I'm sorry, I haven't been programmed to respond to that.")
